name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - run: find *; find * -name '*.pdf' -type f -exec rm -f {} \;

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "tex/*.tex"
          glob_root_file: true
          
      - run: find *
      - run: find * ! -name '*.pdf' ! -name 'Makefile' ! -name '*.tex' -type f -exec rm -f {} \;
      - run: find *
      - run: mkdir -p pdf
      - run: find *
      - run: find * -name '*.pdf' -type f -exec mv {} pdf/. \;
      - run: find *

      - uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: "pdf/*.pdf"

      - name: git commut data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Id github
        run: git config --global user.email ${{env.GIT_COMMIT_AUTHOR_EMAIL}}
        run: git config --global user.name ${{env.GIT_COMMIT_AUTHOR_NAME}}
      - name: Push
        run: git status && git add -A && git commit -m "${{env.GIT_COMMIT_SHORT_SHA}}_BUILD" && git push
