name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: "*.pdf"
  release:
    name: Realease project
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: PDFs
      - name: Test artifact download
        run: ls -R
      - name: git commut data
        uses: rlespinasse/git-commit-data@v1.x

      - name: Print git commit data
        run: |
          echo "commit info" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_SHA }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}" >> AUTHOR
          echo "author info" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}" >> AUTHOR
          echo "committer info" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}" >> AUTHOR
          echo "message info" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}" >> AUTHOR
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}" >> AUTHOR

      - name: PR
        users: peter-evans/create-pull-request@v3 
        with:
          branch: "pdf-update"
          title: "Update PDF"
          committer: ${{ env.GIT_COMMIT_AUTHOR }}
          author: ${{ env.GIT_COMMIT_AUTHOR }}
          token: ${{secrets.GITHUB_TOKEN}}
          delete-branch: true