name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: "*.pdf"
      - name: git commut data
        uses: rlespinasse/git-commit-data-action@v1
      - name: PR
        run: find . ! -name '*.pdf' -type f -exec rm -f {} +
        uses: peter-evans/create-pull-request@v3 
        with:
          branch: ${{env.GIT_COMMIT_SHORT_SHA}} ${{env.GIT_COMMIT_AUTHOR_NAME}}
          base: master
          title: "Update PDF"
          committer: ${{ env.GIT_COMMIT_AUTHOR }}
          author: ${{ env.GIT_COMMIT_AUTHOR }}
          token: ${{secrets.GITHUB_TOKEN}}
          delete-branch: true
  # release:
  #   name: Realease project
  #   runs-on: ubuntu-latest
  #   needs: build_latex
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: PDFs
  #     - name: Test artifact download
  #       run: ls -R

