name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "tex/*.tex"
          glob_root_file: true
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: "*.pdf"
      - run: find * ! -name '*.pdf' ! -name 'Makefile' ! -name '*.tex' -type f -exec rm -f {} +
      - name: git commut data
        uses: rlespinasse/git-commit-data-action@v1

      - name: test
        run: echo "${{ env.GIT_COMMIT_AUTHOR }}"

      - name: PR
        uses: peter-evans/create-pull-request@v3 
        with:
          branch: ${{env.GIT_COMMIT_AUTHOR_NAME}}_${{env.GIT_COMMIT_SHORT_SHA}}
          base: master
          title: "Update PDF"
          committer: ${{ env.GIT_COMMIT_AUTHOR }}
          author: ${{ env.GIT_COMMIT_AUTHOR }}
          token: ${{secrets.GITHUB_TOKEN}}
          delete-branch: true
